// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxNSBw3W__fmZM97ucKa95JVsTQcWQHI',
    appId: '1:823551626955:web:3efbe87a6efb6d10ccd54e',
    messagingSenderId: '823551626955',
    projectId: 'aeon-c06ea',
    authDomain: 'aeon-c06ea.firebaseapp.comq',
    storageBucket: 'aeon-c06ea.firebasestorage.app',
    measurementId: 'G-YQG49GVP1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyA4iVUqa7t6ntWOA_CYO_0tiaqnTbHYk54',
  appId: '1:823551626955:android:aa4b4121fb55e4ebccd54e',
  messagingSenderId: '823551626955',
  projectId: 'aeon-c06ea"',
  storageBucket: 'aeon-c06ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLtYeKbccUXdkxKOjpxyPnW_21R1QKLOk',
    appId: '1:823551626955:ios:c1122425bb5b1d62ccd54e',
    messagingSenderId: '823551626955',
    projectId: 'aeon-c06ea',
    storageBucket: 'aeon-c06ea.firebasestorage.app',
    iosBundleId: 'br.com.aeon.app',
  );

}