// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApQXbAIttiEGmobZWrkrOfNllOlUvVS84',
    appId: '1:15496712239:web:33cd9247cc4a295ad6b6da',
    messagingSenderId: '15496712239',
    projectId: 'aeon-1bdd5',
    authDomain: 'aeon-1bdd5.firebaseapp.com',
    storageBucket: 'aeon-1bdd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVGKv4y-68NCnBPqnixkZCqRIKP2Y8B8',
    appId: '1:15496712239:android:1447a7f242e17c7cd6b6da',
    messagingSenderId: '15496712239',
    projectId: 'aeon-1bdd5',
    storageBucket: 'aeon-1bdd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0-vCV883le8jqxUp5GpVGe-X6bu5zJ0',
    appId: '1:15496712239:ios:948e3ed493067e31d6b6da',
    messagingSenderId: '15496712239',
    projectId: 'aeon-1bdd5',
    storageBucket: 'aeon-1bdd5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0-vCV883le8jqxUp5GpVGe-X6bu5zJ0',
    appId: '1:15496712239:ios:948e3ed493067e31d6b6da',
    messagingSenderId: '15496712239',
    projectId: 'aeon-1bdd5',
    storageBucket: 'aeon-1bdd5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApQXbAIttiEGmobZWrkrOfNllOlUvVS84',
    appId: '1:15496712239:web:a047bd8f2897d8f7d6b6da',
    messagingSenderId: '15496712239',
    projectId: 'aeon-1bdd5',
    authDomain: 'aeon-1bdd5.firebaseapp.com',
    storageBucket: 'aeon-1bdd5.firebasestorage.app',
  );
}
